# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nilxwam/workspace/gwam-simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nilxwam/workspace/gwam-simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nilxwam/workspace/gwam-simulator/CMakeFiles /home/nilxwam/workspace/gwam-simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nilxwam/workspace/gwam-simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named constants

# Build rule for target.
constants: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 constants
.PHONY : constants

# fast build rule for target.
constants/fast:
	$(MAKE) -f CMakeFiles/constants.dir/build.make CMakeFiles/constants.dir/build
.PHONY : constants/fast

#=============================================================================
# Target rules for targets named samlibs

# Build rule for target.
samlibs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 samlibs
.PHONY : samlibs

# fast build rule for target.
samlibs/fast:
	$(MAKE) -f CMakeFiles/samlibs.dir/build.make CMakeFiles/samlibs.dir/build
.PHONY : samlibs/fast

samLibs/constants.o: samLibs/constants.cpp.o
.PHONY : samLibs/constants.o

# target to build an object file
samLibs/constants.cpp.o:
	$(MAKE) -f CMakeFiles/constants.dir/build.make CMakeFiles/constants.dir/samLibs/constants.cpp.o
.PHONY : samLibs/constants.cpp.o

samLibs/constants.i: samLibs/constants.cpp.i
.PHONY : samLibs/constants.i

# target to preprocess a source file
samLibs/constants.cpp.i:
	$(MAKE) -f CMakeFiles/constants.dir/build.make CMakeFiles/constants.dir/samLibs/constants.cpp.i
.PHONY : samLibs/constants.cpp.i

samLibs/constants.s: samLibs/constants.cpp.s
.PHONY : samLibs/constants.s

# target to generate assembly for a file
samLibs/constants.cpp.s:
	$(MAKE) -f CMakeFiles/constants.dir/build.make CMakeFiles/constants.dir/samLibs/constants.cpp.s
.PHONY : samLibs/constants.cpp.s

samLibs/samlibs.o: samLibs/samlibs.cpp.o
.PHONY : samLibs/samlibs.o

# target to build an object file
samLibs/samlibs.cpp.o:
	$(MAKE) -f CMakeFiles/samlibs.dir/build.make CMakeFiles/samlibs.dir/samLibs/samlibs.cpp.o
.PHONY : samLibs/samlibs.cpp.o

samLibs/samlibs.i: samLibs/samlibs.cpp.i
.PHONY : samLibs/samlibs.i

# target to preprocess a source file
samLibs/samlibs.cpp.i:
	$(MAKE) -f CMakeFiles/samlibs.dir/build.make CMakeFiles/samlibs.dir/samLibs/samlibs.cpp.i
.PHONY : samLibs/samlibs.cpp.i

samLibs/samlibs.s: samLibs/samlibs.cpp.s
.PHONY : samLibs/samlibs.s

# target to generate assembly for a file
samLibs/samlibs.cpp.s:
	$(MAKE) -f CMakeFiles/samlibs.dir/build.make CMakeFiles/samlibs.dir/samLibs/samlibs.cpp.s
.PHONY : samLibs/samlibs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... constants"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... samlibs"
	@echo "... samLibs/constants.o"
	@echo "... samLibs/constants.i"
	@echo "... samLibs/constants.s"
	@echo "... samLibs/samlibs.o"
	@echo "... samLibs/samlibs.i"
	@echo "... samLibs/samlibs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

